# Generated by Django 6.0.5 on 2026-05-22 15:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MatchRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('secret_salt', models.CharField(default='mvp_default_salt_123', max_length=64)),
                ('party_a_hashes', models.TextField(blank=True, default='')),
                ('is_party_a_uploaded', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
            ],
        ),
    ]
