# Generated by Django 6.0.5 on 2026-05-22 15:42

import compare.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0002_matchroom_match_count_matchroom_matched_results_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchroom',
            name='invite_token',
            field=models.CharField(default=compare.models.generate_invite_token, editable=False, max_length=64),
        ),
    ]
