# Generated by Django 6.0.5 on 2026-05-22 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0003_matchroom_invite_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchroom',
            name='owner_key',
            field=models.CharField(db_index=True, default='', max_length=64),
        ),
    ]
